version: 0.2

variables:
  DOCKER_REGISTRY: 060494142362.dkr.ecr.us-east-1.amazonaws.com/simpleapp
  APP_NAME: simpleapp
  TAG: "$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID"


phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      # - docker build -t $DOCKER_REGISTRY/$DOCKER_REGISTRY::$TAG .
      - docker build . -t mypythonapp:nagag